LOAN_OFFERS = {
    "000": {
      "id": "000",
      "name": "Starter Pack",
      "desc": "A no-risk starter loan to learn money basics — how you use and repay it shapes your credit score.",
      "type": "ZERO",
      "principal": 2000,
      "repay_amount": 2000,
      "interest_rate": 0.0,
      "term_days": 7,
      "min_lvl": 1,
      "min_credit_score": 0
    },
    "001": {
      "id": "001",
      "name": "Squire’s Advance",
      "desc": "A modest pouch of coin for new adventurers.",
      "type": "FLAT",
      "principal": 2000,
      "repay_amount": 2400,
      "interest_rate": 0,
      "term_days": 7,
      "min_lvl": 7,
      "min_credit_score": 400
    },
    "002": {
      "id": "002",
      "name": "Tavernkeeper’s Tab",
      "desc": "Quick funds to restock and stay afloat.",
      "type": "INTEREST",
      "principal": 5000,
      "repay_amount": 0,
      "interest_rate": 0.015,
      "term_days": 10,
      "min_lvl": 8,
      "min_credit_score": 600
    },
    "003": {
      "id": "003",
      "name": "Apprentice’s Purse",
      "desc": "A small boost to begin your trade route.",
      "type": "FLAT",
      "principal": 8000,
      "repay_amount": 9600,
      "interest_rate": 0,
      "term_days": 12,
      "min_lvl": 10,
      "min_credit_score": 700
    },
    "004": {
      "id": "004",
      "name": "Mercenary’s Stipend",
      "desc": "Coin for supplies before the next contract.",
      "type": "INTEREST",
      "principal": 12000,
      "repay_amount": 0,
      "interest_rate": 0.02,
      "term_days": 14,
      "min_lvl": 12,
      "min_credit_score": 800
    },
    "005": {
      "id": "005",
      "name": "Guild Ledger Loan",
      "desc": "For merchants seeking a steady expansion.",
      "type": "FLAT",
      "principal": 18000,
      "repay_amount": 22500,
      "interest_rate": 0,
      "term_days": 14,
      "min_lvl": 12,
      "min_credit_score": 800
    },
    "006": {
      "id": "006",
      "name": "Baron’s Favor",
      "desc": "A noble-backed loan with noble expectations.",
      "type": "INTEREST",
      "principal": 30000,
      "repay_amount": 0,
      "interest_rate": 0.025,
      "term_days": 18,
      "min_lvl": 15,
      "min_credit_score": 850
    },
    "007": {
      "id": "007",
      "name": "Caravan Investment Writ",
      "desc": "Fund trade ventures and seize market tides.",
      "type": "FLAT",
      "principal": 45000,
      "repay_amount": 58500,
      "interest_rate": 0,
      "term_days": 21,
      "min_lvl": 15,
      "min_credit_score": 850
    },
    "008": {
      "id": "008",
      "name": "Royal Treasury Credit",
      "desc": "High coin, high scrutiny, no room for delay.",
      "type": "INTEREST",
      "principal": 70000,
      "repay_amount": 0,
      "interest_rate": 0.03,
      "term_days": 21,
      "min_lvl": 15,
      "min_credit_score": 850
    },
    "009": {
      "id": "009",
      "name": "Knight-Commander’s Line",
      "desc": "Interest-free coin for the truly trusted.",
      "type": "ZERO",
      "principal": 10000,
      "repay_amount": 10000,
      "interest_rate": 0.0,
      "term_days": 14,
      "min_lvl": 11,
      "min_credit_score": 950
    },
    "010": {
      "id": "010",
      "name": "Dragon Covenant Grant",
      "desc": "A legendary sum offered only to spotless names.",
      "type": "ZERO",
      "principal": 17000,
      "repay_amount": 170000,
      "interest_rate": 0.0,
      "term_days": 30,
      "min_lvl": 15,
      "min_credit_score": 900
    }
  }
