"""Source-controlled seed rows for DB-defined Veyra content.

These rows were copied from the local Veyra database and intentionally filtered
to content referenced by code: starter rewards, lootboxes, smelting resources,
potion recipes/outputs, campaign/quest rewards, and registered usable items.
"""

from domain.battle.gear_shards import shard_item_rows


ITEMS = [
    {
        "item_id": 131,
        "item_name": "Dragon Egg",
        "item_description": "Said to contain untold power, unimaginable riches, or just a very hungry lizard with bad anger issues. Handle at your own risk.",
        "item_rarity": "Epic",
        "item_icon": "https://i.postimg.cc/bvz14Ztd/temp-Image1-MSLIl.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 132,
        "item_name": "Abyssal Feather",
        "item_description": "Plucked from something that should never have wings. It twitches sometimes, even when no wind blows.",
        "item_rarity": "Epic",
        "item_icon": "https://i.postimg.cc/T19KV9t4/temp-Image9-GHg-Ko.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 135,
        "item_name": "Slime in jar",
        "item_description": "His name's Greg. Don't shake Greg.",
        "item_rarity": "Rare",
        "item_icon": "https://i.postimg.cc/ZY2bQXdH/temp-Image-GOo-Hqg.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 148,
        "item_name": "Apples",
        "item_description": "Legends say one bite can change your fate.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/SxZsddWK/temp-Imageyu-LI8-U.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 149,
        "item_name": "Mana Berries",
        "item_description": "Glimmering fruits that pulse with raw magical energy. Eat one and feel your spells surge.",
        "item_rarity": "Rare",
        "item_icon": "https://i.postimg.cc/90xSKD1H/temp-Image-L9l-Uk-C.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 150,
        "item_name": "Shiny Rugs",
        "item_description": "Legends claim it was crafted from dragon hair.",
        "item_rarity": "Rare",
        "item_icon": "https://i.postimg.cc/63FzvCHy/temp-Image3vqzq7.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 153,
        "item_name": "Lanter",
        "item_description": "Burns with an eternal flame, guiding adventurers safely through the darkest caves.",
        "item_rarity": "Rare",
        "item_icon": "https://i.postimg.cc/MpJ44JmZ/temp-Imageu-Mg-N2n.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 157,
        "item_name": "Empty Flask",
        "item_description": "Perfectly empty, endlessly necessary. Alchemists claim no potion will form without one... and none have proven them wrong.",
        "item_rarity": "Rare",
        "item_icon": "https://media.discordapp.net/attachments/921681249817493554/1467505625591185613/image.png",
        "item_durability": None,
        "item_price": 200,
        "item_usable": False,
    },
    {
        "item_id": 158,
        "item_name": "Rabbit Foot",
        "item_description": "Said to bring luck to its bearer, though adventurers still die despite it.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/y8q553zb/temp-Image-SZS6u6.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 160,
        "item_name": "Scraps",
        "item_description": "Leftover bits from past battles, sometimes enough to cobble a weapon or two.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/9Fc1qPVn/temp-Imagew-Zi-PWI.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 161,
        "item_name": "Ancient Cheese",
        "item_description": "Stinky, powerful, and older than anything you have ever seen.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/BbnLJv95/temp-Image7a8d-QR.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 162,
        "item_name": "Rare Candy",
        "item_description": "Perfect for bribing monsters... or your friends' jealousy.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/htWDrGy2/temp-Image-Yj-Fcd-O.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 164,
        "item_name": "Purple Flowers",
        "item_description": "Rare blooms that enhance potions and inspire poets with their mystical aroma.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/28XcRbNk/temp-Image-TAulls.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 166,
        "item_name": "Deer Horn",
        "item_description": "Great for crafting, poking... or politely intimidating woodland creatures.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/hPqxJK8x/temp-Imageso17b7.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 170,
        "item_name": "Bread",
        "item_description": "Freshly baked bread. Eat to gain 100 energy regardless of cap.",
        "item_rarity": "Common",
        "item_icon": "https://i.postimg.cc/xT4PcwCS/temp-Image9-I9-I7-D.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 173,
        "item_name": "Veyra\u2019s Heart",
        "item_description": "Beats in binary, dreams in magic",
        "item_rarity": "Legendary",
        "item_icon": "https://i.postimg.cc/LsTD6ngZ/temp-Image-K1-Vzj0.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 174,
        "item_name": "Laughing Crown",
        "item_description": "Whispers jokes only you find unfunny.",
        "item_rarity": "Legendary",
        "item_icon": "https://i.postimg.cc/B6RMRR1V/temp-Image2vs2q0.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 175,
        "item_name": "Sword Of Dark",
        "item_description": "A blade so edgy it writes poetry about its own loneliness.",
        "item_rarity": "Legendary",
        "item_icon": "https://i.postimg.cc/TPzbxxCH/temp-Image-Wrm-Rw-B.avif",
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 176,
        "item_name": "Wooden Box",
        "item_description": "A basic wooden lootbox. Might contain something useful.",
        "item_rarity": "lootbox",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 177,
        "item_name": "Stone Box",
        "item_description": "A sturdy stone lootbox. Contents are more secure.",
        "item_rarity": "lootbox",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 178,
        "item_name": "Iron Box",
        "item_description": "A heavy iron lootbox. Better chances of rare loot.",
        "item_rarity": "lootbox",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 179,
        "item_name": "Platinum Box",
        "item_description": "A luxurious platinum lootbox. Top-tier rewards inside.",
        "item_rarity": "lootbox",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 180,
        "item_name": "Hint Key",
        "item_description": "Can be used during an ongoing number guessing game. Prevents the next wrong guess from ending the game and gives a hint instead.",
        "item_rarity": "Common",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1434337201381965924/Gemini_Generated_Image_dyx4lgdyx4lgdyx4.png",
        "item_durability": 1,
        "item_price": 10,
        "item_usable": True,
    },
    {
        "item_id": 181,
        "item_name": "Potion of EXP",
        "item_description": "Gives 500 EXP when used.",
        "item_rarity": "Rare",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1434338716758835210/Gemini_Generated_Image_wra7ilwra7ilwra7.png",
        "item_durability": 1,
        "item_price": 50,
        "item_usable": True,
    },
    {
        "item_id": 182,
        "item_name": "Jar of EXP",
        "item_description": "Gives 2000 EXP when used.",
        "item_rarity": "Epic",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1434339639426027590/Gemini_Generated_Image_lvaphnlvaphnlvap.png",
        "item_durability": 1,
        "item_price": 150,
        "item_usable": True,
    },
    {
        "item_id": 183,
        "item_name": "Bag of Gold",
        "item_description": "A small shimmering pouch filled with coins. Use it to gain 100 gold instantly.",
        "item_rarity": "lootbox",
        "item_icon": "https://cdn.discordapp.com/attachments/1354667633336778896/1434439192183832677/Gemini_Generated_Image_4s4bcq4s4bcq4s4b.png?ex=6908551a&is=6907039a&hm=efe15fc5e24043f487f7032fd59301f835f13a7e1caf30a32d20f20f578743c0&",
        "item_durability": 100,
        "item_price": 0,
        "item_usable": True,
    },
    {
        "item_id": 184,
        "item_name": "Copper Ore",
        "item_description": "A rough mineral chunk. Can be refined into Copper Bars by smelting 5 of these.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 185,
        "item_name": "Iron Ore",
        "item_description": "A rough mineral chunk. Can be refined into Iron Bars by smelting 5 of these.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 186,
        "item_name": "Silver Ore",
        "item_description": "A rough mineral chunk. Can be refined into Silver Bars by smelting 5 of these.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 187,
        "item_name": "Coal",
        "item_description": "A chunk of solid fuel. Essential for smelting ores into bars.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 189,
        "item_name": "Copper Bar",
        "item_description": "A refined metal bar formed by combining copper ore. Useful for crafting and selling.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 190,
        "item_name": "Iron Bar",
        "item_description": "A strong metal bar formed by combining iron ore. Commonly traded or sold.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 191,
        "item_name": "Silver Bar",
        "item_description": "A shiny refined bar created from silver ore. Valuable for crafting or selling.",
        "item_rarity": "minerals",
        "item_icon": None,
        "item_durability": None,
        "item_price": None,
        "item_usable": False,
    },
    {
        "item_id": 192,
        "item_name": "Potion of Faster Recovery I",
        "item_description": "A pale blue liquid grimming with soft shimmering rays. Drinking it fills your body with gentle warmth.",
        "item_rarity": "Potion",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1467496027358494865/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 193,
        "item_name": "Potion of Faster Recovery II",
        "item_description": "A brighter azure brew that hums faintly with power, crackling with restless energy.",
        "item_rarity": "Potion",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1467496146636247060/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 194,
        "item_name": "Potion of Faster Recovery III",
        "item_description": "A thick glowing elixir swirling with luminous currents, radiating raw vitality.",
        "item_rarity": "Potion",
        "item_icon": "https://media.discordapp.net/attachments/921681249817493554/1467496469261975656/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 195,
        "item_name": "Potion of Luck I",
        "item_description": "A golden potion that sparkles as if tiny stars are trapped inside.",
        "item_rarity": "Potion",
        "item_icon": "https://media.discordapp.net/attachments/921681249817493554/1467496641912373284/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 196,
        "item_name": "Potion of Luck II",
        "item_description": "A warm amber draught that glows softly, pulsing like a beating heart.",
        "item_rarity": "Potion",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1467496756819398914/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 197,
        "item_name": "Potion of Luck III",
        "item_description": "A radiant liquid swirling with shifting colors, impossible to stare at for long.",
        "item_rarity": "Potion",
        "item_icon": "https://media.discordapp.net/attachments/921681249817493554/1467497019831619781/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 198,
        "item_name": "Potion of Love I",
        "item_description": "A rosy potion swirling with pink mist and faint heart-shaped sparks.",
        "item_rarity": "Potion",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1467497136357638336/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
    {
        "item_id": 199,
        "item_name": "Potion of Hatred I",
        "item_description": "A rosy potion swirling with pink mist and faint heart-shaped sparks.",
        "item_rarity": "Potion",
        "item_icon": "https://cdn.discordapp.com/attachments/921681249817493554/1467497136357638336/image.png",
        "item_durability": None,
        "item_price": None,
        "item_usable": True,
    },
]

ITEMS.extend(shard_item_rows())

UPGRADE_DEFINITIONS = [
    {
        "upgrade_name": "brewing stand",
        "level": 1,
        "cost": 1500,
        "effect_description": "Can brew Tier I potions. A simple stand with flickering flames and rattling glass.",
    },
    {
        "upgrade_name": "brewing stand",
        "level": 2,
        "cost": 3500,
        "effect_description": "Can brew Tier I & II potions. The flames burn steadier, and the glass no longer cracks.",
    },
    {
        "upgrade_name": "brewing stand",
        "level": 3,
        "cost": 8000,
        "effect_description": "Can brew Tier I, II & III potions. The stand hums with unstable alchemical power.",
    },
    {
        "upgrade_name": "inventory",
        "level": 1,
        "cost": 0,
        "effect_description": "Worn Satchel (Lvl 1): Your first sad little bag. But hey, it holds stuff. Slots: 20.",
    },
    {
        "upgrade_name": "inventory",
        "level": 2,
        "cost": 400,
        "effect_description": "Traveler Backpack (Lvl 2): Double the room, double the ambition. Slots: 30 (+10).",
    },
    {
        "upgrade_name": "inventory",
        "level": 3,
        "cost": 1000,
        "effect_description": "Leather Pack (Lvl 3): Proper storage. You're officially not broke. Slots: 40 (+10).",
    },
    {
        "upgrade_name": "inventory",
        "level": 4,
        "cost": 2000,
        "effect_description": "Merchant Bag (Lvl 4): Built for hauling profit. Slots: 55 (+15).",
    },
    {
        "upgrade_name": "inventory",
        "level": 5,
        "cost": 5000,
        "effect_description": "Reinforced Crate (Lvl 5): This thing could survive a dragon sneeze. Slots: 60 (+5).",
    },
    {
        "upgrade_name": "inventory",
        "level": 6,
        "cost": 7000,
        "effect_description": "Caravan Storage (Lvl 6): You're basically running logistics now. Slots: 68 (+8).",
    },
    {
        "upgrade_name": "inventory",
        "level": 7,
        "cost": 10000,
        "effect_description": "Grand Pack of the Guild (Lvl 7): Merchants whisper your name in fear. Slots: 70 (+2).",
    },
    {
        "upgrade_name": "pockets",
        "level": 1,
        "cost": 0,
        "effect_description": "Small Pouch (Lvl 1): A humble pouch with questionable stitching.\\nStack Limits -> Common: 10 | Rare: 5 | Epic: 1 | Legendary: 1 | Minerals: 20 | Lootboxes: 2",
    },
    {
        "upgrade_name": "pockets",
        "level": 2,
        "cost": 500,
        "effect_description": "Deep Pockets (Lvl 2): Your pockets got deeper. So did your greed.\\nStack Limits -> Common: 20 | Rare: 10 | Epic: 3 | Legendary: 1 | Minerals: 30 | Lootboxes: 5",
    },
    {
        "upgrade_name": "pockets",
        "level": 3,
        "cost": 1000,
        "effect_description": "Hidden Compartments (Lvl 3): Totally legal compartments. Probably.\\nStack Limits -> Common: 40 | Rare: 15 | Epic: 5 | Legendary: 1 | Minerals: 35 | Lootboxes: 10",
    },
    {
        "upgrade_name": "pockets",
        "level": 4,
        "cost": 2000,
        "effect_description": "Smuggler Pockets (Lvl 4): You can carry a small economy in here.\\nStack Limits -> Common: 50 | Rare: 20 | Epic: 7 | Legendary: 1 | Minerals: 40 | Lootboxes: 12",
    },
    {
        "upgrade_name": "pockets",
        "level": 5,
        "cost": 8000,
        "effect_description": "Bottomless Pockets (Lvl 5): Reality bends. Inventory cries.\\nStack Limits -> Common: 100 | Rare: 25 | Epic: 10 | Legendary: 2 | Minerals: 50 | Lootboxes: 15",
    },
    {
        "upgrade_name": "smelter",
        "level": 1,
        "cost": 1000,
        "effect_description": "Can smelt Copper using 5 Coal. The furnace wheezes a bit.",
    },
    {
        "upgrade_name": "smelter",
        "level": 2,
        "cost": 650,
        "effect_description": "Can smelt Copper using 4 Coal. The furnace wheezes a bit.",
    },
    {
        "upgrade_name": "smelter",
        "level": 3,
        "cost": 900,
        "effect_description": "Smelts Iron with 4 Coal. Efficiency feels... adequate.",
    },
    {
        "upgrade_name": "smelter",
        "level": 4,
        "cost": 1100,
        "effect_description": "Smelts Iron with 3 Coal. Getting good at this.",
    },
    {
        "upgrade_name": "smelter",
        "level": 5,
        "cost": 1700,
        "effect_description": "Can now smelt Silver using 3 Coal. Shiny profits!",
    },
    {
        "upgrade_name": "smelter",
        "level": 6,
        "cost": 2000,
        "effect_description": "Smelts Silver using 2 Coal. You've achieved eco-friendly capitalism.",
    },
    {
        "upgrade_name": "smelter",
        "level": 7,
        "cost": 3000,
        "effect_description": "Smelts all metals with 1 Coal. Furnace literally flexes on peasants.",
    },
]
